name: Backend Health Check

on:
  pull_request:
    branches:
      - main  # Run on PRs to main

jobs:
  check-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          ./install-venv.sh

      - name: Start backend
        run: |
          source venv/bin/activate
          ./run-backend.sh &

      - name: Wait for backend to start
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:3001/docs && break
            echo "Waiting for backend to start..."
            sleep 3
          done

      - name: Validate API Endpoints
        run: |
          endpoints=(
            "/prompt"
            "/history"
          )
          for endpoint in "${endpoints[@]}"; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3001$endpoint)
            if [ "$response" != "200" ]; then
              echo "❌ Endpoint $endpoint returned $response"
            else
              echo "✔ Endpoint $endpoint is healthy"
            fi
          done
